name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Checkouts the project source code from Git
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: 'http://localhost:5000'
          record: true
          parallel: true

      - name: Deploy to Render
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}

  discord_success_message:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: success()
    steps:
      - uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
          severity: info
          text: "A new version of Pokedex deployed"
          details: "Deployed to https://pokedex-ci-cd-nbas.onrender.com/ by ${{ github.actor }}"


  discord_failure_message:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: failure()
    steps:
      - uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
          severity: error
          text: "Build failed"
          details: "commit ${{github.sha}} by ${{github.actor}} broke the build :("

  tag_release:
    needs: [simple_deployment_pipeline, discord_success_message] # TODO: this job must be done first
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master

